package dictionary.entity;
// Generated 2018/11/20 23:16:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "dictionary")
public class Image implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<ViewSymbolHasImage> viewSymbolHasImages = new HashSet<ViewSymbolHasImage>(
			0);

	public Image() {
	}

	public Image(String name) {
		this.name = name;
	}
	public Image(String name, Set<ViewSymbolHasImage> viewSymbolHasImages) {
		this.name = name;
		this.viewSymbolHasImages = viewSymbolHasImages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
	public Set<ViewSymbolHasImage> getViewSymbolHasImages() {
		return this.viewSymbolHasImages;
	}

	public void setViewSymbolHasImages(
			Set<ViewSymbolHasImage> viewSymbolHasImages) {
		this.viewSymbolHasImages = viewSymbolHasImages;
	}

}
