package dictionary.entity;
// Generated 2018/11/20 3:12:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewSymbolHasClarifierId generated by hbm2java
 */
@Embeddable
public class ViewSymbolHasClarifierId  implements java.io.Serializable {


     private int viewSymbolId;
     private int clarifierId;

    public ViewSymbolHasClarifierId() {
    }

    public ViewSymbolHasClarifierId(int viewSymbolId, int clarifierId) {
       this.viewSymbolId = viewSymbolId;
       this.clarifierId = clarifierId;
    }
   


    @Column(name="view_symbol_id", nullable=false)
    public int getViewSymbolId() {
        return this.viewSymbolId;
    }
    
    public void setViewSymbolId(int viewSymbolId) {
        this.viewSymbolId = viewSymbolId;
    }


    @Column(name="clarifier_id", nullable=false)
    public int getClarifierId() {
        return this.clarifierId;
    }
    
    public void setClarifierId(int clarifierId) {
        this.clarifierId = clarifierId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViewSymbolHasClarifierId) ) return false;
		 ViewSymbolHasClarifierId castOther = ( ViewSymbolHasClarifierId ) other; 
         
		 return (this.getViewSymbolId()==castOther.getViewSymbolId())
 && (this.getClarifierId()==castOther.getClarifierId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getViewSymbolId();
         result = 37 * result + this.getClarifierId();
         return result;
   }   


}


