package dictionary.entity;
// Generated 2018/11/20 3:12:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ViewSymbol generated by hbm2java
 */
@Entity
@Table(name = "view_symbol", catalog = "dictionary")
public class ViewSymbol implements java.io.Serializable {

	private Integer id;
	private MultiviewSymbol multiviewSymbol;
	private String name;
	private Set<ViewSymbolHasClarifier> viewSymbolHasClarifiers = new HashSet<ViewSymbolHasClarifier>(
			0);
	private Set<ViewSymbolHasImage> viewSymbolHasImages = new HashSet<ViewSymbolHasImage>(
			0);

	public ViewSymbol() {
	}

	public ViewSymbol(MultiviewSymbol multiviewSymbol, String name) {
		this.multiviewSymbol = multiviewSymbol;
		this.name = name;
	}
	public ViewSymbol(MultiviewSymbol multiviewSymbol, String name,
			Set<ViewSymbolHasClarifier> viewSymbolHasClarifiers,
			Set<ViewSymbolHasImage> viewSymbolHasImages) {
		this.multiviewSymbol = multiviewSymbol;
		this.name = name;
		this.viewSymbolHasClarifiers = viewSymbolHasClarifiers;
		this.viewSymbolHasImages = viewSymbolHasImages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "multiview_symbol_id", nullable = false)
	public MultiviewSymbol getMultiviewSymbol() {
		return this.multiviewSymbol;
	}

	public void setMultiviewSymbol(MultiviewSymbol multiviewSymbol) {
		this.multiviewSymbol = multiviewSymbol;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "viewSymbol")
	public Set<ViewSymbolHasClarifier> getViewSymbolHasClarifiers() {
		return this.viewSymbolHasClarifiers;
	}

	public void setViewSymbolHasClarifiers(
			Set<ViewSymbolHasClarifier> viewSymbolHasClarifiers) {
		this.viewSymbolHasClarifiers = viewSymbolHasClarifiers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "viewSymbol")
	public Set<ViewSymbolHasImage> getViewSymbolHasImages() {
		return this.viewSymbolHasImages;
	}

	public void setViewSymbolHasImages(
			Set<ViewSymbolHasImage> viewSymbolHasImages) {
		this.viewSymbolHasImages = viewSymbolHasImages;
	}

}
