package dictionary.entity;
// Generated 2018/11/20 23:16:32 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ViewSymbolHasImage generated by hbm2java
 */
@Entity
@Table(name = "view_symbol_has_image", catalog = "dictionary")
public class ViewSymbolHasImage implements java.io.Serializable {

	private ViewSymbolHasImageId id;
	private Image image;
	private ViewSymbol viewSymbol;

	public ViewSymbolHasImage() {
	}

	public ViewSymbolHasImage(ViewSymbolHasImageId id, Image image,
			ViewSymbol viewSymbol) {
		this.id = id;
		this.image = image;
		this.viewSymbol = viewSymbol;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "viewSymbolId", column = @Column(name = "view_symbol_id", nullable = false)),
			@AttributeOverride(name = "imageId", column = @Column(name = "image_id", nullable = false))})
	public ViewSymbolHasImageId getId() {
		return this.id;
	}

	public void setId(ViewSymbolHasImageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", nullable = false, insertable = false, updatable = false)
	public Image getImage() {
		return this.image;
	}

	public void setImage(Image image) {
		this.image = image;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "view_symbol_id", nullable = false, insertable = false, updatable = false)
	public ViewSymbol getViewSymbol() {
		return this.viewSymbol;
	}

	public void setViewSymbol(ViewSymbol viewSymbol) {
		this.viewSymbol = viewSymbol;
	}

}
