package dictionary.entity;
// Generated 2018/11/20 3:12:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewSymbolHasImageId generated by hbm2java
 */
@Embeddable
public class ViewSymbolHasImageId  implements java.io.Serializable {


     private int viewSymbolId;
     private int imageId;

    public ViewSymbolHasImageId() {
    }

    public ViewSymbolHasImageId(int viewSymbolId, int imageId) {
       this.viewSymbolId = viewSymbolId;
       this.imageId = imageId;
    }
   


    @Column(name="view_symbol_id", nullable=false)
    public int getViewSymbolId() {
        return this.viewSymbolId;
    }
    
    public void setViewSymbolId(int viewSymbolId) {
        this.viewSymbolId = viewSymbolId;
    }


    @Column(name="image_id", nullable=false)
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViewSymbolHasImageId) ) return false;
		 ViewSymbolHasImageId castOther = ( ViewSymbolHasImageId ) other; 
         
		 return (this.getViewSymbolId()==castOther.getViewSymbolId())
 && (this.getImageId()==castOther.getImageId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getViewSymbolId();
         result = 37 * result + this.getImageId();
         return result;
   }   


}


